# Generated by Django 4.1.2 on 2023-01-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('participants', models.TextField()),
                ('poster', models.ImageField(blank=True, upload_to='photos/media/%Y/%m/%d/')),
                ('game', models.CharField(max_length=255)),
                ('prize', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket', models.JSONField(blank=True)),
                ('type', models.CharField(choices=[('SE', 'Single elimination'), ('DE', 'Double elimination'), ('RR', 'Round robin')], default='SE', max_length=255)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.tournament')),
            ],
        ),
    ]
