# Generated by Django 4.1.2 on 2024-09-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
