# Generated by Django 4.1.2 on 2023-04-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='final',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='type',
            field=models.CharField(choices=[('SE', 'Single elimination'), ('DE', 'Double elimination'), ('RR', 'Round robin'), ('SW', 'Swiss')], default='SE', max_length=255),
        ),
    ]
