# Generated by Django 4.1.2 on 2023-04-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_bracket_final_alter_bracket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='participants_from_group',
            field=models.IntegerField(default=0),
        ),
    ]
