# Generated by Django 4.1.2 on 2024-09-08 08:34

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2000,1,1)),
            preserve_default=False,
        ),
    ]
