# Generated by Django 4.1.2 on 2024-09-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_match_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='advances_to_next',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='participant_in_match',
            field=models.IntegerField(default=2),
        ),
    ]
