# Generated by Django 4.1.2 on 2024-09-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_remove_bracket_advances_to_next_swbracketsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbracketsettings',
            name='group_bracket',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_time',
        ),
        migrations.AddField(
            model_name='groupbracketsettings',
            name='advance_from_group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupbracketsettings',
            name='group_brackets',
            field=models.ManyToManyField(related_name='group_brackets', to='tournaments.bracket'),
        ),
        migrations.AddField(
            model_name='groupbracketsettings',
            name='participant_in_group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupbracketsettings',
            name='final_bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_brackets', to='tournaments.bracket'),
        ),
    ]
