# Generated by Django 4.1.2 on 2024-09-26 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_remove_groupbracketsettings_group_bracket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 5, 5, 5, 5)),
            preserve_default=False,
        ),
    ]
