# Generated by Django 4.1.2 on 2024-10-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_delete_matchparticipantinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchParticipantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_score', models.IntegerField()),
                ('participant', models.CharField(max_length=255)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='tournaments.match')),
            ],
        ),
    ]
