# Generated by Django 4.1.2 on 2024-11-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_matchparticipantinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
