# Generated by Django 4.1.2 on 2025-01-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_matchparticipantinfo_participant_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='prize',
        ),
        migrations.AlterField(
            model_name='matchparticipantinfo',
            name='participant_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournaments.participantresult'),
        ),
    ]
