# Generated by Django 4.1.2 on 2025-02-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_tournamenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamenttype'),
            preserve_default=False,
        ),
    ]
