# Generated by Django 4.1.2 on 2025-02-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_user'),
        ('tournaments', '0017_rename_admins_tournament_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='followers',
            field=models.ManyToManyField(related_name='subscriptions', to='profiles.profile'),
        ),
    ]
