# Generated by Django 4.1.2 on 2025-02-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_tournament_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.SlugField(max_length=255, unique=True)),
                ('participant_in_match', models.IntegerField(default=2)),
                ('bracket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymus_brackets', to='tournaments.brackettype')),
            ],
        ),
    ]
