# Generated by Django 4.1.2 on 2025-02-14 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_anonymousbracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousbracket',
            name='bracket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_brackets', to='tournaments.brackettype'),
        ),
    ]
