# Generated by Django 4.1.2 on 2025-02-14 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_alter_anonymousbracket_bracket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousbracket',
            name='bracket_type',
        ),
        migrations.RemoveField(
            model_name='anonymousbracket',
            name='participant_in_match',
        ),
        migrations.AddField(
            model_name='anonymousbracket',
            name='bracket',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_bracket', to='tournaments.bracket'),
            preserve_default=False,
        ),
    ]
