# Generated by Django 4.1.2 on 2025-02-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_remove_anonymousbracket_bracket_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.tournament'),
        ),
    ]
